### ISSUE TITLE
Syntax error at line 100

### ISSUE THREAD

**Issue by spkal01** [vjspranav/Jenkins_TelegramBot#3]
File "/data/data/com.termux/files/home/jenkins/bot.py", line 100
    if jenbuild((Token generated in jenkins build), (Job Name), inp):
                                     ^
SyntaxError: invalid syntax

**Comment by spkal01** [comment]
![Screenshot_20201026-190529750~2](https://user-images.githubusercontent.com/65872023/97204123-5e678600-17be-11eb-8d9c-238507135a8e.jpg)

**Comment by vjspranav** [comment]
> File "/data/data/com.termux/files/home/jenkins/bot.py", line 100
> if jenbuild((Token generated in jenkins build), (Job Name), inp):
> ^
> SyntaxError: invalid syntax

That is not an issue with the script, I haven't updated the readme, but there you are supposed to insert a token which you have put for the job in Jenkins which allows remote invocation.
You are supposed to edit and change values accordingly.
Contact me on telegram or mail for help with getting the bot up and running.
I'll be closing this issue now,

**Comment by spkal01** [comment]
Thanks for the assistance may I know your tg username

**Comment by vjspranav** [comment]
> Thanks for the assistance may I know your tg username

vjspranav
